### ISSUE TITLE
Downloadable Version from Kaltura

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/gvp#20]
Quick question. What version (flavor) does the Generic player request when you click the download button? I currently have a video that is still processing and is downloading the original raw file I uploaded to Kaltura. This might be due to it still processing the other flavors, but I wanted to verify.

We should be showing a download for the highest quality version Kaltura created. In most cases this will be the 720p Flavor, also known as "HD/720 - WEB (H264/2500)". And it should fallback to "SD/Large - WEB/MBL (H264/1500)" etc if the larger size is not found.

We do not always upload videos that are optimized for download or playback by end users. In some cases they are huge production files that are intended to just be used for conversion inside of Kaltura.

**Comment by Lin87** [comment]
It's the same download url that used on regular Kaltura player.

Ethan Lin
ethan.lin@uwex.edu<mailto:ethan.lin@uwex.edu>

On Mar 2, 2015, at 12:41 PM, Bryan Bortz <notifications@github.com<mailto:notifications@github.com>> wrote:


Quick question. What version (flavor) does the Generic player request when you click the download button? I currently have a video that is still processing and is downloading the original raw file I uploaded to Kaltura. This might be due to it still processing the other flavors, but I wanted to verify.

We should be showing a download for the highest quality version Kaltura created. In most cases this will be the 720p Flavor, also known as "HD/720 - WEB (H264/2500)". And it should fallback to "SD/Large - WEB/MBL (H264/1500)" etc if the larger size is not found.

We do not always upload videos that are optimized for download or playback by end users. In some cases they are huge production files that are intended to just be used for conversion inside of Kaltura.

-

**Comment by owlboy** [comment]
Actually, it isn't. Here is an example:

GVP - Downloads the original .flv I uploaded to Kaltura
https://media.uwex.edu/content/smgt/smgt325_r12/smgt325_the_future_of_food/

Kaltura Embed - Download the .webm version (Because the skin does not specify a flavor for the download button, and I guess this is what it decided was best):
https://media.uwex.edu/sandbox/bryan/kaltura_download_test.html

When looking at the skin config inside of Kaltura, I can specify what flavor ID is used for the download button. The same should be possible inside of your player.

For reference, here are the Kaltura Flavor IDs again:
![screen shot 2015-03-02 at 2 20 24 pm](https://cloud.githubusercontent.com/assets/237349/6449563/5835e404-c0e7-11e4-8075-28d3653a71f6.png)

**Comment by Lin87** [comment]
Fixed!
