### ISSUE TITLE
Video won't load when marker title is left blank

### ISSUE THREAD

**Issue by n-meyer** [oel-mediateam/gvp#39]
It seems that if a marker is left without a title the video won't load. Is it possible to have markers show up in the player without a title?

![Screen Shot 2019-09-18 at 1 06 04 PM](https://user-images.githubusercontent.com/49766744/65173803-37fce600-da15-11e9-9a8d-e081100790d5.png)

**Comment by Lin87** [comment]
@n-meyer  @owlboy With the current setup, yes and no. Marker name/title is required. It is looking for a value between the opening and closing `marker` tag to supply the tooltip when hovering over the marker. If you didn't put anything there, it returns `undefined`, and the player crashed because `undefined` is nothing. The player is trying to get something that is not there, and the tooltip is trying to get something from nothing.

However, if you put a space there, the player will not crash. Space is a character (it's something), but then you will get an empty tooltip when hovering over the marker. I can have it not showing a tooltip when it is empty, but a VideoJS (the playback library) plugin loads the markers. That means it requires some modifications to the plugin, which takes times.

If it is not urgent, I can revisit this issue later as an enhancement for the next update. Right now, I have a higher priority for another project, which is due very soon.

**Comment by n-meyer** [comment]
@Lin87 @owlboy Thanks for the update! Waiting until the next enhancement sounds good. This issue is not an urgent one. Thanks again!

**Comment by Lin87** [comment]
@n-meyer Will be in the next release, which is coming very soon.
